import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Banner from '../components/banner';

import heroPic from '../public/static/hero.png';
import Card from '../components/card';

export default function Home() {
  const handleOnClick = e => {
    console.log('Clicked');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.heroContainer}>
          <div className={styles.heroImg}>
            <Image src={heroPic} />
          </div>
          <Banner buttonText='view stores nearby' onClick={handleOnClick} />
        </div>
        <div className={styles.cardLayout}>
          <Card
            name='Dutch Bros'
            imgUrl='/static/hero.png'
            href='/coffee-store/dutch-bros'
            className={styles.card}
          />
          <Card
            name='Dutch Bros'
            imgUrl='/static/hero.png'
            href='/coffee-store/dutch-bros'
            className={styles.card}
          />
        </div>
      </main>
    </div>
  );
}
