import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Banner from '../components/banner';

import heroPic from '../public/static/hero.png';
import Card from '../components/card';

import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps(context) {
  // const latLong = '43.65267326999575,-79.39545615725015';
  // const limit = 3;
  // const query = 'coffee store';
  try {
    const response = await fetch(
      'https://api.foursquare.com/v3/places/nearby?ll=36.114647,-115.172813&query=coffee&limit=3', {
        "headers": {
          'authorization': process.env.NEXT_PUBLIC_FOURSQUARE_API_KEY
        }
      });
    // await JSON.parse(response)
    const data = await response.json();
    console.log(data.results);
  } catch (error) {
    console.log(error);
  }

  return {
    props: {
      coffeeStores: coffeeStoresData
    }
  };
}

export default function Home(props) {
  const handleOnClick = e => {
    console.log('Clicked');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.heroContainer}>
          <div className={styles.heroImg}>
            <Image src={heroPic} />
          </div>
          <Banner buttonText='view stores nearby' onClick={handleOnClick} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(store => (
                <Card
                  key={store.id}
                  name={store.name}
                  imgUrl={store.imgUrl}
                  href={`/coffee-store/${store.id}`}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
